# Generated by Django 5.1.4 on 2025-01-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_onetimecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
